slurmstepd: error: task/cgroup: unable to add task[pid=9976] to memory cg '(null)'
=======================
Loading Anaconda Module...
"data":    {'debug': True, 'batch_size': 4, 'num_workers': 5, 'train_dir': '/datasets/SemEval/semeval-2023-task-1-V-WSD-train-v1/train_v1', 'trial_dir': '/datasets/SemEval/semeval-2023-task-1-V-WSD-trial-v1/trial_v1'}
"model":   {'name': 'CLIPFinetune'}
"output":  clip_ft.out
"seed":    12345
"trainer": {'accelerator': 'gpu', 'devices': 1, 'max_epochs': 15, 'precision': 16, 'gradient_clip_val': 1.0, 'val_check_interval': 1.0, 'resume_from_checkpoint': None, 'accumulate_grad_batches': 1, 'num_sanity_val_steps': 0}
/scratch/users/oince22/vwsd/scripts
self.debug: True
Config: "data":    {'debug': True, 'batch_size': 4, 'num_workers': 5, 'train_dir': '/datasets/SemEval/semeval-2023-task-1-V-WSD-train-v1/train_v1', 'trial_dir': '/datasets/SemEval/semeval-2023-task-1-V-WSD-trial-v1/trial_v1'}
"model":   {'name': 'CLIPFinetune'}
"output":  /scratch/users/oince22/vwsd/scripts/clip_ft.out
"seed":    12345
"trainer": {'accelerator': 'gpu', 'devices': 1, 'max_epochs': 15, 'precision': 16, 'gradient_clip_val': 1.0, 'val_check_interval': 1.0, 'resume_from_checkpoint': None, 'accumulate_grad_batches': 1, 'num_sanity_val_steps': 0}
Error executing job with overrides: []
Traceback (most recent call last):
  File "/scratch/users/oince22/vwsd/scripts/clip_ft_pred.py", line 49, in <module>
    main()
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/scratch/users/oince22/vwsd/scripts/clip_ft_pred.py", line 35, in main
    trainer = pl.Trainer(
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 340, in insert_env_defaults
    return fn(self, **kwargs)
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 408, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 211, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
  File "/kuacc/users/oince22/.conda/envs/vwsd/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 517, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
lightning_lite.utilities.exceptions.MisconfigurationException: No supported gpu backend found!
